### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by XanXus96** [Claudemirovsky/worstsource-keys#2]
Hello, i've been trying to deofbuscate this while i found this repo (m on the consumet discord too) i just wanna note some stuff that i found:

the embed script does change every hour at xx:00:10, and the version query parameter is the timestap of xx:00:10 converted to Hex so: 
- no need to make a call to ${vidplayHost}/e/ as we now know what the version code will be every time
- no need to call the action every 10 minutes as the script changes every hour

**Comment by Claudemirovsky** [comment]
Thanks bro!
